Update earth_volcanoes_pixels.yml
Fixed bug: File "*/dora/.venv/lib/python3.8/site-packages/dora_exp_pipeline/outlier_detection.py", line 69, in run
    results = self._rank_internal(dtf, dts, dts_ids, top_n, seed, **kwargs)
TypeError: _rank_internal() missing 1 required positional argument: 'fit_single_trees'